// export const ActionTypes = {
//     SET_PRODUCTS: "SET_PRODUCT_DETAILS",
//     SELECTED_PRODUCT: "SELECTED_PRODUCT",
//     REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
//   };
export const SET_PRODUCT_DETAILS = 'SET_PRODUCT_DETAILS';

export const GET_PRODUCTS = 'GET_PRODUCTS'